name: .NET

on:
  push:
    tags: 
      - '*'
jobs:
  build:
    runs-on: windows-2022
    steps:
    - name: Install maui-check
      run: dotnet tool install -g Redth.Net.Maui.Check
      shell: pwsh
    - name: maui-check
      run: maui-check --preview --ci --non-interactive --fix --skip xcode --skip vswin --skip vsmac --skip edgewebview2
      shell: pwsh
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: |
        $VERION=$env:GITHUB_REF.Substring($env:GITHUB_REF.LastIndexOf('/') + 1)
        echo "PACKAGE VERSION: $VERSION"
        dotnet build --no-restore -p:PackageVersion=$VERSION
    # - name: Pack
    #   run: dotnet pack --include-symbols -o ./nuget
    # - name: Publish
    #   run: dotnet nuget push .\nuget\*.nupkg -s "nuget.org" -k ${{ secrets.NUGET_API_KEY }}
